export const GET_POKEMONS = 'GET_POKEMONS';
export const PUT_POKEMONS = 'PUT_POKEMONS';
export const PUT_PAGINATION = 'PUT_PAGINATION';

export const GET_SINGLE_POKEMON = 'GET_SINGLE_POKEMON';
export const PUT_SINGLE_POKEMON = 'PUT_SINGLE_POKEMON';

export const GET_SINGLE_MOVE = 'GET_SINGLE_MOVE';
export const PUT_SINGLE_MOVE = 'PUT_SINGLE_MOVE';

export const FETCH_ERROR = 'FETCH_ERROR';
